
/* Bar Chart and Map Example Query for ABMVIZ HTML5 */
/* Ben Stabler, ben.stabler@rsginc.com, 12/8/15 */

/* Set Scenario  */
ALTER USER [ATLANTAREGION\TAMConsult] WITH DEFAULT_SCHEMA = BS10

/* Trips by zone, county, mode */
SELECT ORIG_TAZ AS ZONE, MIN(COUNTYNAMES.NAME) AS COUNTY, TRIP_MODE_NAME AS "TRIP MODE", COUNT(TRIP_MODE_NAME) AS QUANTITY 
FROM TRIPS, ZONEDATA, COUNTYNAMES
WHERE TRIPS.ORIG_TAZ=ZONEDATA.ZONE AND ZONEDATA.COUNTY=COUNTYNAMES.CODE 
GROUP BY ORIG_TAZ, TRIP_MODE_NAME

UNION

/* Total trips by zone, county */
SELECT ORIG_TAZ AS ZONE, MIN(COUNTYNAMES.NAME) AS COUNTY, 'TOTAL', COUNT(*) AS QUANTITY 
FROM TRIPS, ZONEDATA, COUNTYNAMES
WHERE TRIPS.ORIG_TAZ=ZONEDATA.ZONE AND ZONEDATA.COUNTY=COUNTYNAMES.CODE 
GROUP BY ORIG_TAZ
ORDER BY ZONE, TRIP_MODE_NAME