
/* TreeMap example query for ABMVIZ HTML5 */
/* Ben Stabler, ben.stabler@rsginc.com, 07/08/16 */

/* Set Scenario  */
ALTER USER [ATLANTAREGION\TAMConsult] WITH DEFAULT_SCHEMA = BS10

/* Creates SIMPLEMODES (simplified mode groupings) table */
IF EXISTS (SELECT * FROM sys.objects, sys.schemas WHERE sys.objects.schema_id=sys.schemas.schema_id and sys.objects.name = 'SimpleModes')
	BEGIN
		DROP TABLE SimpleModes
	END

CREATE TABLE SimpleModes (ModeName VARCHAR(50), NestModeName VARCHAR(50), SimpleModeName VARCHAR(50))
INSERT INTO SimpleModes VALUES ('DRIVEALONEFREE','DRIVEALONE','AUTO')
INSERT INTO SimpleModes VALUES ('DRIVEALONEPAY','DRIVEALONE','AUTO')
INSERT INTO SimpleModes VALUES ('SHARED2FREE','SHARED2','AUTO')
INSERT INTO SimpleModes VALUES ('SHARED2PAY','SHARED2','AUTO')
INSERT INTO SimpleModes VALUES ('SHARED3FREE','SHARED3','AUTO')
INSERT INTO SimpleModes VALUES ('SHARED3PAY','SHARED3','AUTO')
INSERT INTO SimpleModes VALUES ('WALK','NONMOTORIZED','NONMOTORIZED')
INSERT INTO SimpleModes VALUES ('BIKE','NONMOTORIZED','NONMOTORIZED')
INSERT INTO SimpleModes VALUES ('PNR_ALLTRN','PNR','TRANSIT')
INSERT INTO SimpleModes VALUES ('PNR_PRMTRN','PNR','TRANSIT')
INSERT INTO SimpleModes VALUES ('WALK_PRMTRN','WALK_TRANSIT','TRANSIT')
INSERT INTO SimpleModes VALUES ('WALK_ALLTRN','WALK_TRANSIT','TRANSIT')
INSERT INTO SimpleModes VALUES ('KNR_ALLTRN','KNR','TRANSIT')
INSERT INTO SimpleModes VALUES ('KNR_PRMTRN','KNR','TRANSIT')
INSERT INTO SimpleModes VALUES ('SCHOOL_BUS','SCHOOL_BUS','SCHOOL_BUS')

/* Trips by mode in order to create the Tree Map (square pie chart) visual */  
SELECT SIMPLEMODENAME AS "TRIPS BY MODE", NESTMODENAME AS "NEST MODE", TRIP_MODE_NAME AS "SIMPLE MODE", COUNT(TRIP_MODE_NAME) AS QUANTITY
FROM TRIPS, SIMPLEMODES
WHERE TRIPS.TRIP_MODE_NAME=SIMPLEMODES.MODENAME
GROUP BY SIMPLEMODENAME, NESTMODENAME, TRIP_MODE_NAME 
ORDER BY SIMPLEMODENAME, NESTMODENAME, TRIP_MODE_NAME	